apiVersion: v1
kind: Service
metadata:
  name: java-cicd-svc
  labels:
    version: 1.0.0
spec:
  selector:
    app: java-cicd-api
  ports:
    - port: 8080
      nodePort: 31888  # <-- Use a value between 30000-32767
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cicd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-cicd-api
  template:
    metadata:
      labels:
        app: java-cicd-api   
    spec:
      containers:
        - name: java-cicd-demo
          image: registry.azurecr.io/javacicd:<SERVICE_VERSION>
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: -Xmx512M
          resources:
            requests:
              memory: "1G"
            limits:
              memory: "4G"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 20
            periodSeconds: 60
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
      imagePullSecrets:
        - name: regcred # create a secret with your azure/registry creds if the registry is private.
      nodeSelector:
        kubernetes.io/os: linux
